-- MySQL Script generated by MySQL Workbench
-- Sun Feb  3 12:54:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema homeko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homeko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeko` DEFAULT CHARACTER SET utf8 ;
USE `homeko` ;

-- -----------------------------------------------------
-- Table `homeko`.`additionalInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`additionalInfo` ;

CREATE TABLE IF NOT EXISTS `homeko`.`additionalInfo` (
  `additionalInfoID` INT NOT NULL AUTO_INCREMENT,
  `additionalInfoName` VARCHAR(70) NOT NULL,
  `additionalInfoType` INT NOT NULL,
  PRIMARY KEY (`additionalInfoID`))
ENGINE = InnoDB;

CREATE INDEX `infoType` ON `homeko`.`additionalInfo` (`additionalInfoType` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`area` ;

CREATE TABLE IF NOT EXISTS `homeko`.`area` (
  `areaID` INT NOT NULL AUTO_INCREMENT,
  `areaName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`areaID`))
ENGINE = InnoDB;

CREATE INDEX `areaName` ON `homeko`.`area` (`areaName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`contact` ;

CREATE TABLE IF NOT EXISTS `homeko`.`contact` (
  `contactID` INT NOT NULL AUTO_INCREMENT,
  `contactNo` VARCHAR(11) NOT NULL,
  `ownerID` INT NOT NULL,
  PRIMARY KEY (`contactID`),
  CONSTRAINT `ownerID`
    FOREIGN KEY (`ownerID`)
    REFERENCES `homeko`.`owner` (`ownerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `ownerID_idx` ON `homeko`.`contact` (`ownerID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`feedback` ;

CREATE TABLE IF NOT EXISTS `homeko`.`feedback` (
  `feedbackID` INT NOT NULL AUTO_INCREMENT,
  `housingID` INT NOT NULL,
  `comment` VARCHAR(500) NOT NULL,
  `status` INT NOT NULL,
  `datePosted` DATE NOT NULL,
  PRIMARY KEY (`feedbackID`),
  CONSTRAINT `housingID`
    FOREIGN KEY (`housingID`)
    REFERENCES `homeko`.`housing` (`housingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `status` ON `homeko`.`feedback` (`status` ASC) VISIBLE;

CREATE INDEX `housingID_idx` ON `homeko`.`feedback` (`housingID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`houseType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`houseType` ;

CREATE TABLE IF NOT EXISTS `homeko`.`houseType` (
  `houseTypeID` INT NOT NULL AUTO_INCREMENT,
  `houseTypeName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`houseTypeID`))
ENGINE = InnoDB;

CREATE INDEX `typeName` ON `homeko`.`houseType` (`houseTypeName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`housing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`housing` ;

CREATE TABLE IF NOT EXISTS `homeko`.`housing` (
  `housingID` INT NOT NULL AUTO_INCREMENT,
  `housingName` VARCHAR(50) NOT NULL,
  `area` INT NOT NULL,
  `address` VARCHAR(80) NOT NULL,
  `propertyType` INT NOT NULL,
  `houseType` INT NOT NULL,
  `mapHTML` VARCHAR(500) NULL,
  `creationDate` DATE NOT NULL,
  `createdBy` VARCHAR(45) NOT NULL,
  `lastEditedDate` VARCHAR(45) NOT NULL,
  `lastEditedBy` DATE NOT NULL,
  PRIMARY KEY (`housingID`),
  CONSTRAINT `propertyType`
    FOREIGN KEY (`propertyType`)
    REFERENCES `homeko`.`propertyType` (`propertyTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `houseType`
    FOREIGN KEY (`houseType`)
    REFERENCES `homeko`.`houseType` (`houseTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `area`
    FOREIGN KEY (`area`)
    REFERENCES `homeko`.`area` (`areaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `propertyType_idx` ON `homeko`.`housing` (`propertyType` ASC) VISIBLE;

CREATE INDEX `houseType_idx` ON `homeko`.`housing` (`houseType` ASC) VISIBLE;

CREATE INDEX `area_idx` ON `homeko`.`housing` (`area` ASC) VISIBLE;

CREATE INDEX `housingName` ON `homeko`.`housing` (`housingName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`housingAdditionalInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`housingAdditionalInfo` ;

CREATE TABLE IF NOT EXISTS `homeko`.`housingAdditionalInfo` (
  `housingAdditionalInfoID` INT NOT NULL AUTO_INCREMENT,
  `additionalInfoID` INT NOT NULL,
  `description` VARCHAR(300) NULL,
  `housingID` INT NOT NULL,
  PRIMARY KEY (`housingAdditionalInfoID`),
  CONSTRAINT `additionalInfoID`
    FOREIGN KEY (`additionalInfoID`)
    REFERENCES `homeko`.`additionalInfo` (`additionalInfoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `housingID`
    FOREIGN KEY (`housingID`)
    REFERENCES `homeko`.`housing` (`housingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `additionalInfoID_idx` ON `homeko`.`housingAdditionalInfo` (`additionalInfoID` ASC) VISIBLE;

CREATE INDEX `housingID_idx` ON `homeko`.`housingAdditionalInfo` (`housingID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`housingOwner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`housingOwner` ;

CREATE TABLE IF NOT EXISTS `homeko`.`housingOwner` (
  `housingOwnerID` INT NOT NULL AUTO_INCREMENT,
  `housingID` INT NOT NULL,
  `ownerID` INT NOT NULL,
  PRIMARY KEY (`housingOwnerID`),
  CONSTRAINT `housingID`
    FOREIGN KEY (`housingID`)
    REFERENCES `homeko`.`housing` (`housingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ownerID`
    FOREIGN KEY (`ownerID`)
    REFERENCES `homeko`.`owner` (`ownerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `housingID_idx` ON `homeko`.`housingOwner` (`housingID` ASC) VISIBLE;

CREATE INDEX `ownerID_idx` ON `homeko`.`housingOwner` (`ownerID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`housingRequest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`housingRequest` ;

CREATE TABLE IF NOT EXISTS `homeko`.`housingRequest` (
  `housingRequestID` INT NOT NULL AUTO_INCREMENT,
  `requestID` INT NOT NULL,
  `housingID` INT NOT NULL,
  PRIMARY KEY (`housingRequestID`),
  CONSTRAINT `requestID`
    FOREIGN KEY (`requestID`)
    REFERENCES `homeko`.`request` (`requestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `housingID`
    FOREIGN KEY (`housingID`)
    REFERENCES `homeko`.`housing` (`housingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `requestID_idx` ON `homeko`.`housingRequest` (`requestID` ASC) VISIBLE;

CREATE INDEX `housingID_idx` ON `homeko`.`housingRequest` (`housingID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`owner` ;

CREATE TABLE IF NOT EXISTS `homeko`.`owner` (
  `ownerID` INT NOT NULL AUTO_INCREMENT,
  `ownerName` VARCHAR(70) NOT NULL,
  `firstName` VARCHAR(40) NOT NULL,
  `lastName` VARCHAR(40) NOT NULL,
  `email` VARCHAR(60) NULL,
  PRIMARY KEY (`ownerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeko`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`picture` ;

CREATE TABLE IF NOT EXISTS `homeko`.`picture` (
  `pictureID` INT NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(30) NOT NULL,
  `housingID` INT NOT NULL,
  PRIMARY KEY (`pictureID`),
  CONSTRAINT `housingID`
    FOREIGN KEY (`housingID`)
    REFERENCES `homeko`.`housing` (`housingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `housingID_idx` ON `homeko`.`picture` (`housingID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`propertyType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`propertyType` ;

CREATE TABLE IF NOT EXISTS `homeko`.`propertyType` (
  `propertyTypeID` INT NOT NULL AUTO_INCREMENT,
  `propertyTypeName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`propertyTypeID`))
ENGINE = InnoDB;

CREATE INDEX `typeName` ON `homeko`.`propertyType` (`propertyTypeName` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `homeko`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homeko`.`request` ;

CREATE TABLE IF NOT EXISTS `homeko`.`request` (
  `requestID` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `status` INT NOT NULL,
  `dateSent` DATE NOT NULL,
  `sender` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`requestID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
