# Generated by Django 2.1.5 on 2019-02-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalinfo',
            fields=[
                ('additionalinfoid', models.AutoField(db_column='additionalInfoID', primary_key=True, serialize=False)),
                ('additionalinfoname', models.CharField(db_column='additionalInfoName', max_length=70)),
                ('additionalinfotype', models.IntegerField(db_column='additionalInfoType')),
            ],
            options={
                'db_table': 'additionalInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaid', models.AutoField(db_column='areaID', primary_key=True, serialize=False)),
                ('areaname', models.CharField(db_column='areaName', max_length=30)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactid', models.AutoField(db_column='contactID', primary_key=True, serialize=False)),
                ('contactno', models.CharField(db_column='contactNo', max_length=11)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(db_column='feedbackID', primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('dateposted', models.DateField(db_column='datePosted')),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Housetype',
            fields=[
                ('housetypeid', models.AutoField(db_column='houseTypeID', primary_key=True, serialize=False)),
                ('housetypename', models.CharField(db_column='houseTypeName', max_length=20)),
            ],
            options={
                'db_table': 'houseType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('housingid', models.AutoField(db_column='housingID', primary_key=True, serialize=False)),
                ('housingname', models.CharField(db_column='housingName', max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('maphtml', models.CharField(blank=True, db_column='mapHTML', max_length=500, null=True)),
                ('creationdate', models.DateField(db_column='creationDate')),
                ('createdby', models.CharField(db_column='createdBy', max_length=45)),
                ('lastediteddate', models.CharField(db_column='lastEditedDate', max_length=45)),
                ('lasteditedby', models.DateField(db_column='lastEditedBy')),
            ],
            options={
                'db_table': 'housing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerid', models.AutoField(db_column='ownerID', primary_key=True, serialize=False)),
                ('ownername', models.CharField(db_column='ownerName', max_length=70)),
                ('firstname', models.CharField(db_column='firstName', max_length=40)),
                ('lastname', models.CharField(db_column='lastName', max_length=40)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propertytype',
            fields=[
                ('propertytypeid', models.AutoField(db_column='propertyTypeID', primary_key=True, serialize=False)),
                ('propertytypename', models.CharField(db_column='propertyTypeName', max_length=20)),
            ],
            options={
                'db_table': 'propertyType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestid', models.AutoField(db_column='requestID', primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('datesent', models.DateField(db_column='dateSent')),
                ('sender', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
    ]
