# Generated by Django 2.1.5 on 2019-02-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingAdditionalInfo',
            fields=[
                ('housingadditionalinfoid', models.AutoField(db_column='housingAdditionalInfoID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=300)),
            ],
            options={
                'db_table': 'housingadditionalinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousingOwner',
            fields=[
                ('housingownerid', models.AutoField(db_column='HousingOwnerID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'housingowner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousingRequest',
            fields=[
                ('housingrequestid', models.AutoField(db_column='HousingRequestID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'housingrequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pictureid', models.AutoField(db_column='pictureID', primary_key=True, serialize=False)),
                ('filename', models.CharField(db_column='fileName', max_length=30)),
            ],
            options={
                'db_table': 'picture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomCost',
            fields=[
                ('roomid', models.AutoField(db_column='roomID', primary_key=True, serialize=False)),
                ('roomname', models.CharField(db_column='roomName', max_length=100)),
                ('cost', models.FloatField(db_column='cost')),
            ],
            options={
                'db_table': 'roomcost',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='additionalinfo',
            table='additionalinfo',
        ),
        migrations.AlterModelTable(
            name='housetype',
            table='housetype',
        ),
        migrations.AlterModelTable(
            name='propertytype',
            table='propertytype',
        ),
    ]
