# Generated by Django 2.1.5 on 2019-02-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20190205_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={},
        ),
    ]
